### PR TITLE
feat: add max voting power per pool

### PR DESCRIPTION
**Pull request by shifty11**
## Summary by CodeRabbit

- **New Features**
  - Introduced a new parameter `MaxVotingPowerPerPool` to manage the maximum voting power per pool.

- **Documentation**
  - Updated API documentation to include the new `max_voting_power_per_pool` field.

- **Bug Fixes**
  - Adjusted error message for `ErrVotingPowerTooHigh` to reflect the new voting power limits.

- **Refactor**
  - Improved parameter setting logic in test scenarios for better maintainability and clarity.

- **Tests**
  - Added new test cases to validate the functionality of the `MaxVotingPowerPerPool` parameter.

### CODE REVIEW

**Review by troykessler — CHANGES_REQUESTED** [review]
Please also add the max voting per pool parameter in the `x/bundles/keeper/msg_server_update_params_test.go` test file

**Review by troykessler — CHANGES_REQUESTED** [review]
Finally, add the new pool parameter to the x/pool/spec/05_params.md spec file, else everything looks good

**Comment by shifty11** [comment]
> Please also add the max voting per pool parameter in the `x/bundles/keeper/msg_server_update_params_test.go` test file

You mean in `x/pool/keeper/msg_server_update_params_test.go` ? There are no param changes in the bundles module... so not sure what to add there.

**Comment by troykessler** [comment]
> > Please also add the max voting per pool parameter in the `x/bundles/keeper/msg_server_update_params_test.go` test file
> 
> You mean in `x/pool/keeper/msg_server_update_params_test.go` ? There are no param changes in the bundles module... so not sure what to add there.

Yep you're right, all good then

**Review by troykessler — APPROVED** [review]

**Pull request merged**
