### PR TITLE
chore(dev-deps): update ledger-cosmos-go from v0.12.2 to v0.12.4 and ledger-go from v0.14.1 to v0.14.3

### PR DESCRIPTION
**Pull request by zakarialounes**
Please see:

- https://github.com/cosmos/cosmos-sdk/issues/18319
- https://github.com/cosmos/cosmos-sdk/issues/18423#issuecomment-1804129041

### CODE REVIEW

**Comment by mbreithecker** [comment]
Hey @zakarialounes ,
thanks for the PR. However, I think your fork is out of sync, the ledger dependencies were already updated in this PR: https://github.com/KYVENetwork/chain/pull/139

**Comment by zakarialounes** [comment]
Indeed, I started from tag v1.3.1. So I'm closing this PR since it's of no use. Thank you.

**Comment by zakarialounes** [comment]
What's strange @mbreithecker is that GitHub detects a change, since it allowed me to create the PR. I'll leave it to you to check whether the change is actually there.

**Comment by zakarialounes** [comment]
I thought that GitHub would detect that the changes were already there, but obviously it's having trouble. Since the changes are there, I'm closing the PR.

**Comment by mbreithecker** [comment]
You are right, this is indeed very strange. I also did a diff on my local machine and apparently Github is having some troubles.

**Pull request closed without merging**
