### PR TITLE
feat: prioritize protocol txs

### PR DESCRIPTION
**Pull request by shifty11**
## Summary by CodeRabbit

- **New Features**
  - Introduced a priority proposal handler to manage transaction prioritization for block proposals.

- **Configuration Changes**
  - Restructured funding details in the `genesis` section to specify denominations and adjust total funded values.

- **Tests**
  - Added comprehensive test cases for transaction handling and order verification in the proposal handler.
  - Updated test utilities for proposal handling and upgrade testing.
  - Modified denominations in reward and withdrawal reward tests to "zcoin" and "ycoin".

These updates enhance transaction management and improve the clarity and accuracy of funding configurations.

### CODE REVIEW

**Review by troykessler — CHANGES_REQUESTED** [review]
I'm not sure why this is the case but according the the cometbft docs PrepareProposal can receive transactions where the total byte size can exceed the max_tx_bytes:

> CometBFT MAY include a list of transactions in RequestPrepareProposal.txs whose total size in bytes exceeds RequestPrepareProposal.max_tx_bytes. Therefore, if the size of RequestPrepareProposal.txs is greater than RequestPrepareProposal.max_tx_bytes, the Application MUST remove transactions to ensure that the RequestPrepareProposal.max_tx_bytes limit is respected by those transactions returned in ResponsePrepareProposal.txs .

https://docs.cometbft.com/v0.37/spec/abci/abci++_methods#prepareproposal

maybe a check should be added and when the max byte size is reached the last transactions in the defaultQueue should be dropped

**Comment by shifty11** [comment]
> I'm not sure why this is the case but according the the cometbft docs PrepareProposal can receive transactions where the total byte size can exceed the max_tx_bytes:
> 
> > CometBFT MAY include a list of transactions in RequestPrepareProposal.txs whose total size in bytes exceeds RequestPrepareProposal.max_tx_bytes. Therefore, if the size of RequestPrepareProposal.txs is greater than RequestPrepareProposal.max_tx_bytes, the Application MUST remove transactions to ensure that the RequestPrepareProposal.max_tx_bytes limit is respected by those transactions returned in ResponsePrepareProposal.txs .
> 
> https://docs.cometbft.com/v0.37/spec/abci/abci++_methods#prepareproposal
> 
> maybe a check should be added and when the max byte size is reached the last transactions in the defaultQueue should be dropped

I added a check for this in the proposal handler (and one test)

**Review by troykessler — DISMISSED** [review]

**Comment by mbreithecker** [comment]
We will move this PR to v1.6
From our understanding, cometBFT already limits the input depending on the tx size. So currently we only sort a fixed (pre-selected) set of transactions. What one would need to do, is to set the max-tx-size in the cometBFT params to -1 to forward every transaction to the application layer. Here, we would then need to sort by priority and cut depending on the size. 
Setting this param to -1 and handling everything our self is indeed a little critical and requires a lot of testing, therefore we will move it to 1.6

**Comment by mbreithecker** [comment]
Will be cancelled for now, as this features is considered low priority and involves critical code aspects (transactions-handling)

**Pull request closed without merging**
